CREATE TABLE abrigos (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nome VARCHAR2(100) NOT NULL,
    telefone VARCHAR2(14) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    CONSTRAINT abrigos_pk PRIMARY KEY (id),
    CONSTRAINT abrigos_nome_unique UNIQUE (nome),
    CONSTRAINT abrigos_telefone_unique UNIQUE (telefone),
    CONSTRAINT abrigos_email_unique UNIQUE (email)
);
