CREATE TABLE pets (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    tipo VARCHAR2(100) NOT NULL,
    nome VARCHAR2(100) NOT NULL,
    raca VARCHAR2(100) NOT NULL,
    idade INT NOT NULL,
    cor VARCHAR2(100) NOT NULL,
    peso DECIMAL(4,2) NOT NULL,
    abrigo_id NUMBER NOT NULL,
    adotado CHAR(1) NOT NULL CHECK (adotado IN ('Y', 'N')),
    CONSTRAINT pets_pk PRIMARY KEY (id),
    CONSTRAINT fk_pets_abrigo_id FOREIGN KEY (abrigo_id) REFERENCES abrigos (id)
);
