CREATE TABLE adocoes (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    data TIMESTAMP NOT NULL,
    tutor_id NUMBER NOT NULL,
    pet_id NUMBER NOT NULL,
    motivo VARCHAR2(255) NOT NULL,
    status VARCHAR2(100) NOT NULL,
    justificativa_status VARCHAR2(255),
    CONSTRAINT adocoes_pk PRIMARY KEY (id),
    CONSTRAINT fk_adocoes_tutor_id FOREIGN KEY (tutor_id) REFERENCES tutores (id),
    CONSTRAINT fk_adocoes_pet_id FOREIGN KEY (pet_id) REFERENCES pets (id)
);
